### PR TITLE
Format Code in User.cs

### PR DESCRIPTION
**Pull request by lindexi**
The "{" in Id is the same line with the definition.

### CODE REVIEW

**Comment by oldnewthing** [comment]
I normally don't make pure formatting changes. This avoids unnecessary churn.

**Comment by lindexi** [comment]
I can not agree with you more @oldnewthing. But the samples repo will serve as a reference for other developers when writing code. The code needs to conform to standard coding conventions to make the developers can take this code to share and learn with standard coding conventions.

In [corefx/coding-style.md at master · dotnet/corefx](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md ) NO.1, we use Allman style braces, where each brace begins on a new line. A single line statement block can go without braces but the block must be properly indented on its own line and must not be nested in other statement blocks that use braces (See issue 381 for examples). One exception is that a using statement is permitted to be nested within another using statement by starting on the following line at the same indentation level, even if the nested using contains a controlled block.

**Comment by oldnewthing** [comment]
I doubt one misplaced brace is going to confuse people. When any future changes are made to this sample, we can fix the brace then.

**Comment by lindexi** [comment]
@oldnewthing I agree one misplaced brace can not confuse people. But there is a [Broken windows theory ](https://en.wikipedia.org/wiki/Broken_windows_theory ).

**Comment by oldnewthing** [comment]
There is also the "avoid making the repo bigger" theory. A large repo is less likely to be cloned. I spent many months shrinking the repo down from its original size of 176MB. I am very conscious of repo size.

**Pull request closed without merging**
