### PR TITLE
Logging samples updated

### PR DESCRIPTION
**Pull request by littlecegian**
1. templates are updated.
2. moderncop errors fixed
3. wack errors fixed.
4. template errors from SD fixed

### CODE REVIEW

**Comment by oldnewthing** [comment]
Sorry, the dev branch is locked. Please hold this change in your local rep and submit a new pull request when dev reopens.

**Comment by littlecegian** [comment]
Thank you Raymond. How/Where can I learn when the dev branch will open
again ?

On Wed, Jun 17, 2015 at 3:23 PM, Raymond Chen <notifications@github.com>
wrote:

> Sorry, the dev branch is locked. Please hold this change in your local rep
> and submit a new pull request when dev reopens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/Windows-universal-samples/pull/74#issuecomment-112968908>
> .
>



-- 



Thanks,
Ravi Sankar Raju,
Software Engineer,
Operating Systems Group, Microsoft.

**Comment by oldnewthing** [comment]
Work with your samples SME.

**Comment by littlecegian** [comment]
Thank you!

On Thu, Jun 18, 2015 at 12:40 PM, Raymond Chen <notifications@github.com>
wrote:

> Work with your samples SME.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/Windows-universal-samples/pull/74#issuecomment-113268480>
> .
>



-- 



Thanks,
Ravi Sankar Raju,
Software Engineer,
Operating Systems Group, Microsoft.

**Pull request closed without merging**
