### PR TITLE
Fixed some coding style issues in ApplicationData solution.

### PR DESCRIPTION
**Pull request by gcsizmadia**
I applied the followings:
- When using a built-in type itself I used its C# alias but when using its static method I used its class name, eg. string output = String.Format(...);
- Removed unnecessary "this" qualifications.
- Removed unnecessary namespace qualifications.
- Removed unnecessarily specified Exception type from catch blocks
- Simplified some boolean expressions.
- Reduced nesting code

### CODE REVIEW

**Comment by washcycle** [comment]
Just a thought, but 

•Removed unnecessary "this" qualifications.
•Removed unnecessary namespace qualifications.

might be unnecessary, but could be useful to novice developers. Which might have been the intent.

**Comment by gcsizmadia** [comment]
Could be true but I cannot really see in what way they can be useful, especially if they are not applied everywhere just in some parts of the code.

I think it may be more confusing for novice developers to have these unnecessary qualifications at some place and do not have them at some other place where they could also be applied. They might come to a wrong conclusion.

I think not these code samples are supposed to demonstrate how many (unnecessary) things can we avoid to write thanks to the smart C# compiler. :)

I think the code we provide should have a coding style as professional as possible so that novice developers can learn from that. Of course the code itself should be as simple and easy to understand as possible.

And if one has difficulties in understanding the code then there is always the option for everyone - including novice developers - to hover the cursor over a method call or a parameter type to see which class or namespace it belongs to.

**Comment by oldnewthing** [comment]
Generally, we try to write samples so they are readable even to those who are not familiar with a language, because these samples are often the basis for translation to other languages (see the other discussions around VB and F#). Also, hovering over a method call to see its type doesn't work so great when you are reading the sample in a Web browser.

**Comment by gcsizmadia** [comment]
That is why we should (at least try to) write the code in a unified way according to the C# guidelines and best practises.

There are more options:
- We might provide VB.NET code samples as well (as seen at some other place, e.g. MSDN) - also in a unified way according to the VB.NET guidelines and best practises.
- One may use an online C# <--> VB.NET converter that might be not 100% perfect but can give one the idea.
- One may learn the OOP / C# basics first before trying to write UWP apps.

I think the changes I made did not make the code readabilty worse even if one is not familiar with the C# language and even if it is read in a Web browser.

If someone would like to know anything about the details of a method / type / etc. then he/she should load the code sample into Visual Studio. I think it is part of learning. Anyway, the code sample cannot be tried out from the Web browser.

I do not think that we should write C# code in VB.NET / F# / Java / PHP / etc. style so that the code might be a bit readable to those developers.

If one would like to translate from one language to another language it can be assumed that he/she already has or would like to get (at least) a basic knowledge in both languages.

**Comment by ChrisGuzak** [comment]
these changes seem reasonable to me.

**Comment by oldnewthing** [comment]
> When using a built-in type itself I used its C# alias but when using its static method I used its class name, eg. string output = String.Format(...);

What coding standard is this? I find it confusing. Should pick one or the other, not switch based on how the type is used.

**Comment by gcsizmadia** [comment]
> What coding standard is this? I find it confusing. Should pick one or the other, not switch based on how the type is used.

I understand your concerns, it might be confusing, but I really like the concept behind this coding style, which is very simple and I think reasonable.

When we need the indication of the type we use the C# keyword / alias.
```csharp
public string DoSomething(string someParameter)
{
    string result;
    // Doing something
    return result;
}
```

When we need to call a static method or to retrieve the value of a static property we use the CLR type name which looks more like a class due to the Pascal casing than the lowercase keyword, eg.
```csharp
return someCondition ? String.Empty : String.Format(...);
```

Consider enum vs Enum. They are not interchangeable.
```csharp
// "enum" must be used
enum Color { Red, Green, Blue }

// Causes "Unexpected token" error
Enum Color { Red, Green, Blue }

Color ParseColor(string value)
{
    // "Enum" must be used
    return (Color)Enum.Parse(typeof(Color), value);

    // Causes error
    return (Color)enum.Parse(typeof(Color), value);
}

int ParseInt32(string value)
{
    // Can be used and looks consistent when considering Enum.Parse(...)
    // The method name also contains Int32 according to Microsoft's naming convention.
    return Int32.Parse(value);

    // Can also be used but looks inconsistent when considering Enum.Parse(...)
    // In my opinion it looks a bit weird that a keyword has a callable method.
    return int.Parse(value);
}
```

The support of this coding style is also requested from ReSharper and I agree with them.

**Pull request closed without merging**
