### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NormR**
Testing

### CODE REVIEW

**Comment by NormR** [comment]
Testing

**Comment by oldnewthing** [comment]
Could you do your testing in your fork rather than the main repo? Thanks.

**Comment by NormR** [comment]
Sorry to interfere with your stuff.  The Windows-universal-samples was in my respositories.  I do not know github  and was just practicing with something I found in my repository and didn't know how or why it got there.
Norm

________________________________

**Comment by oldnewthing** [comment]
No problem.

**Comment by NormR** [comment]
I've removed Windows-universal-samples from my list of repositories so it won't happen again.
Norm

________________________________

**Pull request closed without merging**
