### PR TITLE
Adding a Windows Holographic sample which shows how to switch between an XAML view and an exclusive view

### PR DESCRIPTION
**Pull request by adamrankin**
Code is based on the HolographicTagAlong and basic XAML application template code. Credit to NajaDojo (https://forums.hololens.com/profile/NajaDojo) for inspiring me to create the sample (posted here: https://forums.hololens.com/discussion/250/how-to-switch-from-2d-xaml-view-to-3d-holographic-view-directx)

### CODE REVIEW

**Comment by adamrankin** [comment]
I realize I don't know if you accept external samples. Let me know if you need any more information or details about what I wrote.

I kept the same overall structure as other samples, used the SharedContent MainPage and App structure along with a scenario page.

I've been learning this stuff face-first, and the few Holographic samples here were invaluable (face tracking sample, especially!), so I figured other people may appreciate more.

**Comment by oldnewthing** [comment]
We would require a contributor license agreement to accept samples from the general public. The responsible feature team would also have to review it.

**Comment by adamrankin** [comment]
Ok, up to you guys! I have completed a contribution license agreement (I think).

Cheers.

**Comment by adamrankin** [comment]
Hello, I know this is an old contribution, but I wanted to follow up on it.

I have signed the agreement.

**Pull request closed without merging**
