### PR TITLE
Add lowLevel DeviceCapability to IoT samples

### PR DESCRIPTION
**Pull request by jordanrh1**
The lowLevel device capability is required to access GPIO, I2C, SPI.

### CODE REVIEW

**Comment by jordanrh1** [comment]
@oldnewthing Please let me know if you have any feedback.

**Comment by oldnewthing** [comment]
I'll look at it at the end of the month.

**Comment by jordanrh1** [comment]
Ping

**Comment by oldnewthing** [comment]
Hi. Sorry haven't had time to look at these in a while. I'll need to ask the feature team to review this PR.

**Comment by jordanrh1** [comment]
I am the feature team :)

**Comment by oldnewthing** [comment]
All right then!

**Comment by oldnewthing** [comment]
Pulled into staging repo.

**Pull request closed without merging**
