### PR TITLE
Add code "to call tryEnterFullScreenMode when clicking full screeen b…

### PR DESCRIPTION
**Pull request by nksato**
…utton on <video>."

### CODE REVIEW

**Comment by zherman** [comment]
Hi Naoki Sato,

Is there a reason you did not add full screen mode specific logic to the resize event handler (handleResize)?

**Comment by nksato** [comment]
Hi zherman,
To be same behaviour as 1) VideoPlayback(CS) and 2) web browser app.

Clicking full screen button on Xaml/mediaelement, viedo area do swich full screen mode.
However, clicking full screen button on <video> tag, video area do not switch full screen mode.

**Comment by zherman** [comment]
When the view changes its full screen mode value (either by exiting or entering full screen mode) and handleResize is called should there be special logic with regards to the UI layout and internal state or was it an intentional decision to not add logic into the resize event handler?

**Comment by nksato** [comment]
Clicking "max button" on video player do not fire resize event.

**Comment by zherman** [comment]
The code below mentions that a resize event will be raised when exit and enter full screen mode complete. Are you saying this does not occur?

        if (view.isFullScreenMode) {
            view.exitFullScreenMode();
            // The resize event will be raised when the exit from full screen mode is complete.
        } else {
            if (view.tryEnterFullScreenMode()) {
               // The resize event will be raised when the entry to full screen mode is complete.
            } else {
            }
        }

**Comment by nksato** [comment]
No.  When clicking max button on "video" tag, window.resize event not fired.

>Is there a reason you did not add full screen mode specific logic to the resize event handler (handleResize)?

click max button on "video" player
 -> fire webkitfullscreenchange event
   -> call view.tryEnterFullScreenMode or view.exitFullScreenMode on onToggleFullScreenMode()
    -> fire resize event
     ->(handleResize())

**Comment by nksato** [comment]
Sorry,

**Comment by oldnewthing** [comment]
This change doesn't belong in the standard template. It belongs in the webview sample. (And Windows Store apps use Chakra, they don't raise webkit events.)

**Pull request closed without merging**
